name: Trigger Modal Run

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger downstream workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy.yml
