name: Deploy to Modal

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      MODAL_CONFIG_DIR: /home/runner/.modal

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Modal SDK
        run: pip install --upgrade modal

      - name: Inject Modal Token
        run: |
          mkdir -p $MODAL_CONFIG_DIR
          echo -e "[default]" > $MODAL_CONFIG_DIR/token.toml
          echo -e "token_id = \"$MODAL_TOKEN_ID\"" >> $MODAL_CONFIG_DIR/token.toml
          echo -e "token_secret = \"$MODAL_TOKEN_SECRET\"" >> $MODAL_CONFIG_DIR/token.toml

      - name: Deploy and run on Modal
        run: modal run deploy.py
