name: Deploy to Modal

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Modal CLI
        run: pip install modal

      - name: Set Modal Token
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
        run: |
          mkdir -p ~/.modal
          echo -e "[default]\ntoken_id = \"${MODAL_TOKEN_ID}\"\ntoken_secret = \"${MODAL_TOKEN_SECRET}\"" > ~/.modal/token.toml
          echo "Token file written."

      - name: Deploy via Modal CLI
        run: modal deploy deploy.py
